### ISSUE TITLE
Opening any File Causes Error

### ISSUE THREAD

**Issue by ToddAlvord** [paulpflug/foldername-tabs#19]
[Enter steps to reproduce:]

1. Any file I open causes the error below to occur.

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: 'tab-foldername-index' package vundefined

### Stack Trace

Uncaught TypeError: Cannot read property 'add' of null

```
At /Users/toddalvord/.atom/packages/tab-foldername-index/lib/main.js:173

TypeError: Cannot read property 'add' of null
    at Object.addTab (/packages/tab-foldername-index/lib/main.js:173:31)
    at realTimeout (/packages/tab-foldername-index/lib/main.js:105:36)
```

### Commands

```
  4x -0:44.4.0 core:backspace (input.hidden-input)
     -0:40.6.0 core:save (input.hidden-input)
  6x -0:37.9.0 core:move-left (input.hidden-input)
     -0:36.5.0 core:save (input.hidden-input)
  2x -0:32.8.0 core:move-right (input.hidden-input)
     -0:31.4.0 core:delete (input.hidden-input)
     -0:30.9.0 core:save (input.hidden-input)
  2x -0:26.1.0 core:backspace (input.hidden-input)
     -0:25.2.0 core:save (input.hidden-input)
     -0:18.3.0 core:delete (input.hidden-input)
     -0:17.9.0 core:save (input.hidden-input)
  2x -0:16.4.0 core:backspace (input.hidden-input)
     -0:15.8.0 core:save (input.hidden-input)
     -0:13.4.0 core:move-right (input.hidden-input)
  7x -0:13.1.0 core:move-left (input.hidden-input)
     -0:07.9.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
color-picker 2.3.0 
compare-files 0.8.1 
dash 1.7.1 
file-icons 2.1.21 
foldername-tabs 0.2.4 
git-blame 1.6.0 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
pigments 0.40.2 
react 0.18.0 
sort-lines 0.18.0 
sync-settings 0.8.6 
testing-syntax 0.0.0 
```

**Comment by ToddAlvord** [comment]
Not sure what was going on. I was testing a few different tab name addons, looks like the error above wasnt even for this addon, but one that I uninstalled that didnt get unloaded properly or something. Restarting atom fixed the issue.
